### ISSUE TITLE
adduser from function results in current user being replaced by random data - can cause segfault

### ISSUE THREAD

**Issue by Grandomthoughts** [unix-ninja/hackersandbox#2]
Attempting to add a user to a vm through a function based on a file set as executable.
(function condensed to bare minimum to show issue)

-- load test VM
newVM ("test")
setProperty( { ip = "1.1.1.1" })
setProperty ({ on_root = "f_test_root", hint = "Test"  })
addFile ({ name = "/bin/addu", content = garbage(10), exec="addu", acl="777"})
addUser ( "root", "toor" )

function f_test_root()
end

function addu()
  addUser ( "jeff", "password" )
end

function intro()
  login ({ host = "test", user = "root"})
end
--end mission pack

----- Terminal Sandbox Loading mission pack - steps to segfault
./sandbox function.mis
Loading mission pack (function.mis)...
$ whoami
root
$ /bin/addu 
$ whoami
�R�
$ cd /home
$ ls
jeff/
$ cd jeff
Segmentation fault
----
The problem seems to be related to line 335 of vm.cpp when the new user is added to the user vector.  
edit: the push_back to users vector can cause the reallocation of memory, breaking the pointer for the user_chain.  Reserving the memory in the VM like users.reserve(64); fixes this issue.

**Comment by unix-ninja** [comment]
Hey, thanks for reporting this! As you mentioned, the problem was with the `users` store getting reallocated in memory, which caused the pointers in `user_chain` to invalidate. It would have been nice to just use on `users.reserve()` to fix this one, however C++ wants to be a little smarter than me. `vector::reserve` will only adjust the capacity for the scope; after which, it gets reset to the size of the vector. In this case, the capacity only lasts for the VM constructor, which is pretty useless.

After considering a few different ways to fix this, I ended up just recalculating the chain after the `users` store gets updated. It seems to work on Linux and macOS for me.
